### ISSUE TITLE
Using modified classy code

### ISSUE THREAD

**Issue by runburg** [CobayaSampler/cobaya#228] opened 2022-01-19 23:59 UTC
Hi,

So I'm trying to use a modified version of CLASS with Cobaya. I have the modified version of CLASS compiled and working with the python wrapper (I can import from a python file and set new parameters and compute cosmologies with these modified components). As far as I understand it, this version of classy has been installed *globally* (since I can `import classy` from my python script and get the correct version.

However, when I try and use cobaya, I get 
```
Error in Class: Class did not read input parameter(s): ***my new parameters***
```
even though the output says 
```
[classy] Importing *auto-installed* CLASS (but defaulting to *global*).
```
I'm sure this is an easy solve but any help would be much appreciated! Thanks!

**Comment by JesusTorrado** [comment] 2022-01-22 14:01
Hi @runburg 

That's a tricky one. Unless you give `classy` a `path` property in the input, Cobaya prefers the auto-installed one over the global one. The design idea was that most of the time users would be specifying paths to their modified versions, since they may have more than one around.

You have two options:
- use the aforementioned `path` option in the `theory: classy` block.
- delete the auto-installed CLASS.

Closing since it's not a bug, but please do update us here, and feel free to re-open if it feels appropriate.

**Closed by JesusTorrado** 2022-01-22 14:01 UTC

**Comment by runburg** [comment] 2022-01-25 19:58
Hi, I'm still struggling with this...I've tried to set the path property but I haven't figured out which path to use to make this work. I was just assuming I should point it to the path of the folder with the classy cython .so file but this is apparently not working. 

Where should I be pointing cobaya to?

**Comment by runburg** [comment] 2022-01-27 01:13
Okay this worked thanks! I was trying to point to the library directly. Pointing to the base folder of the CLASS installation worked.

**Comment by IamSreeman** [comment] 2022-07-12 23:25
@runburg can you specify how you gave the path? Is it like this?

```
theory:
  classy:
    path: '/home/sreeman/class_public'
    extra_args:
      non linear: hmcode
      nonlinear_min_k_max: 20
      N_ncdm: 1
      N_ur: 2.0328
```

**Comment by runburg** [comment] 2022-07-12 23:44
Yes that looks right if class_public is your modified CLASS code.
