### ISSUE TITLE
Issue with finding paramters of my model.

### ISSUE THREAD

**Issue by sureshparekh** [CobayaSampler/cobaya#302] opened 2023-07-15 10:40 UTC
Dear Developers,

I am new to this library and I am trying to learn its working by simulating simple models but face issue in understanding the documentation. I wrote a code but it isn't working. The below image shows the equation.

![image](https://github.com/CobayaSampler/cobaya/assets/53847845/a4048073-e10a-4774-b1ad-48eed9e414c1)

I am trying to use this equation. I provide H and z as the input (observational data). I want to find the alpha, beta and gamma parameter, then calculate the Ho accordingly and plot them  using getdist.Below is the code which I tried to make.

[test1.txt](https://github.com/CobayaSampler/cobaya/files/12061162/test1.txt)

Please help me understand the working of this library and if possible share some example related to this problem which I am trying to workout.

Thanks and Regards,
Suresh Parekh

**Comment by cmbant** [comment] 2023-07-16 17:12
Closing, not a bug report

**Closed by cmbant** 2023-07-16 17:12 UTC
