### ISSUE TITLE
Problem when running minimizer after sampling

### ISSUE THREAD

**Issue by mraveri** [CobayaSampler/cobaya#323] opened 2023-10-12 17:41 UTC
I am trying to run the minimizer after sampling, within a Python script that looks something like this:

```
# copy in parameters:
_params = copy.deepcopy(params)
_params['sampler'] = mcmc_options

# run MCMC chain:
updated_info, sampler = run(_params)

# copy in parameters:
_params = copy.deepcopy(params)
_params['sampler'] = minimize_options

# run minimizer like this
updated_info, sampler = run(_params)
# or like this
updated_info, sampler = run(_params, minimize=True)
```

This keeps complaining that the parameters have changed (as they should) and the run cannot continue. 
Is this intended? What would be the proper syntax to do so?

This is being run with several MPI instances.

**Comment by cmbant** [comment] 2023-10-12 19:13
This code gives a None error at check_force_resume (and seems compliant with what we currently say in the docs)

```
import cobaya
from cobaya import run
info = {"likelihood": {"one": None}} # the same as above

info["params"] = dict([
    ["a", {"prior": {"min": -10, "max": 10},"ref":1,"proposal":0.001}], # the same as above
    ["b", {"prior": {"min": 0, "max": 20} ,"ref":2, "proposal":0.001}],
    ["c", {"prior": {"min": 0, "max":100},"ref":3,"proposal": 0.01}],
    ["sv", {"prior": {"min": 0, "max": 1},"ref":0.1,"proposal":0.0001}]])

info["sampler"] = {
    "mcmc": {"burn_in": 500, "max_samples": 1000000, "Rminus1_stop": 0.1}} # the same as above
info["output"]= 'z:\\testchain'

updated_info, products = run(info)

info["sampler"] = {
    "minimize": {} # the same as above
}
updated_info, products = run(info)
```

**Comment by mraveri** [comment] 2023-10-12 20:33
This code:

```
import cobaya
from cobaya import run
info = {"likelihood": {"one": None}} # the same as above

info["params"] = dict([
    ["a", {"prior": {"min": -10, "max": 10},"ref":1,"proposal":0.001}], # the same as above
    ["b", {"prior": {"min": 0, "max": 20} ,"ref":2, "proposal":0.001}],
    ["c", {"prior": {"min": 0, "max":100},"ref":3,"proposal": 0.01}],
    ["sv", {"prior": {"min": 0, "max": 1},"ref":0.1,"proposal":0.0001}]])

info["sampler"] = {
    "mcmc": {"burn_in": 500, "max_samples": 1000000, "Rminus1_stop": 0.1}} # the same as above
info["output"]= 'z:\\testchain'

updated_info, products = run(info)

updated_info, products = run(info, minimize=True)
```

reports

```
[input] is_equal_info: different blocks or options: {'theory', 'likelihood', 'params'} (old) vs {'likelihood', 'params', 'minimize'} (new)
```

and is the second problem I found

**Comment by JesusTorrado** [comment] 2023-10-13 09:59
@mraveri Thanks for reporting. Indeed the argument `minimize` of the `run` function is not handled correctly. Please don't use it, and instead set the sampler as `{"minimize": {}}`.

@cmbant I think the problem is that the argument `minimize` of the `run` function is not handled correctly internally: it should not be passed to the `load_info_overrides` function, which will set it as a key of the `info`, instead of as the sampler, and produce this sort of errors. I'll write a PR

**Comment by cmbant** [comment] 2023-10-28 10:02
Another old issue is that the .updated.yaml and input.yaml have the same name when running minimize runs, presumably should have distinct names if we support using the output root, or have both samplers with either running order. Because of this, you currently can't minimize and then run chains with -r as the infos are incompatible.

**Comment by cmbant** [comment] 2023-10-30 23:24
I think all these issues are resolved by generating the minimize yaml with the "minimize" infix, so all the files are distinct. i.e. passing on infix here: https://github.com/CobayaSampler/cobaya/blob/master/cobaya/output.py#L353
Not trying to put multiple samplers in the same yaml seems the easiest solution for the moment.

I've implemented this fix in https://github.com/CobayaSampler/cobaya/pull/326

**Closed** 2023-11-21 16:22 UTC
