### ISSUE TITLE
Taking massive neutrinos into account with a given matter density

### ISSUE THREAD

**Issue by prakharbansal16** [CobayaSampler/cobaya#384] opened 2024-09-24 07:06 UTC
I wanted to know how does cobaya handle the massive neutrinos when the matter density and baryon density are the given parameters? Actually I'm trying to reproduce exact CAMB results for the sound horizon at recombination and theta_* parameter. I tried replicating the values by considering the massless neutrino case and that works pretty well but the for the massive neutrino case even my hubble's constant doesn't agree with CAMB results. In my hubble's constant expression, I add the relativistic neutrino contribution `(omega_nu_rel = 0.2271*2.0313*omega_gamma)` (I'm using 2.0313 because that's what CAMB outputs for the massless fraction for the case with 2 massless and 1 massive eigenstate) to the radiation density and doesn't add any massive neutrino contribution to the matter density since it already account for it by definition. Is this interpretation correct or does CAMB does something else for the massive neutrino case?

**Comment by cmbant** [comment] 2024-09-24 07:12
Please give short code that shows exactly what you are trying to do. However this sounds more like a  CAMB question than Cobaya - Cobaya just sends the parameters you git it to CAMB.

**Comment by prakharbansal16** [comment] 2024-09-24 08:00
These are the two functions that I'm using. I want to calculate E (1090, [omegam, ombh2, H0]) for a parameter set omegam, ombh2 and H0. 

```
def nu_relative_density(z):
    n_eff = 3.046
    c= 2.99792458*(10**5)
    m_nu = 0.06 #eV
    kb =  1.380649e-23
    T_nu0 = 1.945*kb/1.6e-19 #eV
    a = 1/(1+z)
    y = m_nu*a/T_nu0
    f_val = 120/(7*np.pi**4)*integrate.quad(lambda x: x**2*np.sqrt(x**2+y**2)/(np.exp(x)+1),0,np.inf)[0]
    #return 0.2271*n_eff/3*(2+f_val)  
     return 0.2271*2.0331
  
def E(z, parameters):   #Flat lambdaCDM universe
    omega = parameters[0]
    H0 = parameters[1]
    #omega_r = 4.94e-5
    omega_lambda = 1-omega

        
    omega_rh2 = 2.4729753310411856e-5*(1+nu_relative_density(z)) 
    omega_r = omega_rh2/(H0/100)**2
    omega_lambda = 1-omega-omega_r
    
    return np.sqrt(((omega)*((1+z)**3))+ omega_r*(1+z)**4 +omega_lambda)
```
What I'm confused about is  the massive  neutrino contribution included in the nu_relative_density or is it already accounted for in omega_m in CAMB? My apologies for posting it in this thread insted of the CAMB thread

**Comment by cmbant** [comment] 2024-09-24 08:11
Omega_m in camb includes massive neutrinos. Closing this as not Cobaya and not a bug.

**Closed by cmbant** 2024-09-24 08:11 UTC
