### ISSUE TITLE
resuming with PolyChord not working

### ISSUE THREAD

**Issue by lukashergt** [CobayaSampler/cobaya#39] opened 2019-09-09 14:51 UTC
Trying to resume a PolyChord run currently fails with (full output further down):

```bash
forrtl: severe (64): input conversion error, unit 10, file /home/lh561/Documents/Projects/CobayaPrj/chains/sn_pantheon/class_pc16_sn/raw_polychord_output/class_pc16_sn.resume
```

I've encountered this at first with the Planck likelihood (for both CAMB and CLASS), but it can be reproduced very fast with a SN likelihood and a small `nlive` (i.e. run once and interrupt, then try running again with `-r`).

The full output from the attempt to resume with `cobaya-run -r -d`:
```
(py36env) lh561@login-e-12:~/Documents/Projects/CobayaPrj$cobaya-run -r -d input/class_pc16_sn.yaml
 2019-09-09 15:40:01,306 [output] Output to be read-from/written-into folder 'chains/sn_pantheon/class_pc16_sn', with prefix 'class_pc16_sn'
 2019-09-09 15:40:01,306 [output] Found existing products with the requested ouput prefix: 'chains/sn_pantheon/class_pc16_sn/class_pc16_sn'
 2019-09-09 15:40:01,307 [output] Let's try to resume/load.
 2019-09-09 15:40:01,394 [run] Input info updated with defaults (dumped to YAML):
theory:
  classy:
    extra_args:
      N_ur: 2.0328
      N_ncdm: 1
    path: null
    renames:
      As: A_s
      ns: n_s
      nrun: alpha_s
      nrunrun: beta_s
      nt: n_t
      ntrun: alpha_t
      rdrag: rs_drag
      omegak: Omega_k
      omegal: Omega_Lambda
      w: w0_fld
      wa: wa_fld
      omegabh2: omega_b
      omegab: Omega_b
      omegach2: omega_cdm
      omegac: Omega_cdm
      omegam: Omega_m
      omegan: Omega_nu
      tau: tau_reio
      zrei: z_reio
      deltazrei: reionization_width
      helium_redshift: helium_fullreio_redshift
      helium_delta_redshift: helium_fullreio_width
      yhe: YHe
      yheused: YHe
    speed: 0.2
    use_planck_names: false
likelihood:
  sn.pantheon:
    dataset_file: Pantheon/full_long.dataset
    dataset_params: null
    params: []
    path: null
    renames:
    - Pantheon
    - Pantheon18
    speed: 100
sampler:
  polychord:
    base_dir: raw_polychord_output
    blocking: null
    boost_posterior: 0
    callback_function: null
    cluster_posteriors: true
    compression_factor: 0.36787944117144233
    confidence_for_unbounded: 0.9999995
    do_clustering: true
    equals: true
    feedback: null
    file_root: null
    logzero: null
    max_ndead: .inf
    nlive: 16
    nprior: null
    num_repeats: 5d
    path: null
    posteriors: true
    precision_criterion: 0.001
    read_resume: true
    seed: null
    write_dead: true
    write_live: true
    write_resume: true
    write_stats: true
params:
  logA:
    prior:
      min: 2.5
      max: 3.7
    ref:
      dist: norm
      loc: 3.1
      scale: 0.001
    proposal: 0.001
    latex: \log(10^{10} A_\mathrm{s})
    drop: true
  A_s:
    value: 'lambda logA: 1e-10*np.exp(logA)'
    latex: A_\mathrm{s}
    derived: true
    renames:
    - As
  n_s:
    prior:
      min: 0.885
      max: 1.04
    ref:
      dist: norm
      loc: 0.96
      scale: 0.004
    proposal: 0.002
    latex: n_\mathrm{s}
    renames:
    - ns
  H0:
    prior:
      min: 40
      max: 100
    ref:
      dist: norm
      loc: 70
      scale: 2
    proposal: 2
    latex: H_0
  omega_b:
    prior:
      min: 0.019
      max: 0.025
    ref:
      dist: norm
      loc: 0.0221
      scale: 0.0001
    proposal: 0.0001
    latex: \Omega_\mathrm{b} h^2
    renames:
    - omegabh2
  omega_cdm:
    prior:
      min: 0.095
      max: 0.145
    ref:
      dist: norm
      loc: 0.12
      scale: 0.001
    proposal: 0.0005
    latex: \Omega_\mathrm{c} h^2
    renames:
    - omegach2
  Omega_m:
    latex: \Omega_\mathrm{m}
    derived: true
    renames:
    - omegam
  omegamh2:
    derived: 'lambda Omega_m, H0: Omega_m*(H0/100)**2'
    latex: \Omega_\mathrm{m} h^2
  m_ncdm:
    renames: mnu
    value: 0.06
  Omega_Lambda:
    latex: \Omega_\Lambda
    derived: true
    renames:
    - omegal
  YHe:
    latex: Y_\mathrm{P}
    derived: true
    renames:
    - yheused
    - yhe
  tau_reio:
    prior:
      min: 0.01
      max: 0.4
    ref:
      dist: norm
      loc: 0.09
      scale: 0.01
    proposal: 0.005
    latex: \tau_\mathrm{reio}
    renames:
    - tau
  z_reio:
    latex: z_\mathrm{re}
    derived: true
    renames:
    - zrei
output: class_pc16_sn
resume: true
timing: true
modules: /rds/user/lh561/hpc-work/data/CobayaData/modules
debug: true
force: false

 2019-09-09 15:40:01,581 [likelihood] Parameters were assigned as follows:
 2019-09-09 15:40:01,581 [likelihood] - 'sn.pantheon':
 2019-09-09 15:40:01,581 [likelihood]      Input:  []
 2019-09-09 15:40:01,581 [likelihood]      Output: []
 2019-09-09 15:40:01,581 [likelihood] - 'theory':
 2019-09-09 15:40:01,581 [likelihood]      Input:  ['A_s', 'n_s', 'H0', 'omega_b', 'omega_cdm', 'm_ncdm', 'tau_reio']
 2019-09-09 15:40:01,581 [likelihood]      Output: ['Omega_m', 'Omega_Lambda', 'YHe', 'z_reio']
 2019-09-09 15:40:01,582 [classy] Importing *local* classy from /rds/user/lh561/hpc-work/data/CobayaData/modules/code/classy
 2019-09-09 15:40:01,585 [sn.pantheon] Reading /rds/user/lh561/hpc-work/data/CobayaData/modules/data/sn_data/Pantheon/lcparam_full_long_zhel.txt
 2019-09-09 15:40:01,598 [sn.pantheon] Number of SN read: 1048 
 2019-09-09 15:40:01,598 [sn.pantheon] Reading covmat for: mag 
 2019-09-09 15:40:05,517 [likelihood] The theory code will compute the following products, requested by the likelihoods: ['Omega_m', 'Omega_Lambda', 'YHe', 'z_reio', 'angular_diameter_distance']
 2019-09-09 15:40:05,535 [polychord] Initializing
 2019-09-09 15:40:05,535 [polychord] Importing *local* PolyChord from /rds/user/lh561/hpc-work/data/CobayaData/modules/code/PolyChordLite
 2019-09-09 15:40:05,555 [polychord] Storing raw PolyChord output in 'chains/sn_pantheon/class_pc16_sn/raw_polychord_output'.
 2019-09-09 15:40:05,556 [likelihood] Optimal ordering of parameter blocks: [['logA', 'n_s', 'H0', 'omega_b', 'omega_cdm', 'tau_reio']] with speeds array([1])
 2019-09-09 15:40:05,559 [polychord] Calling PolyChord with arguments:
 2019-09-09 15:40:05,559 [polychord]   base_dir: chains/sn_pantheon/class_pc16_sn/raw_polychord_output
 2019-09-09 15:40:05,559 [polychord]   boost_posterior: 0
 2019-09-09 15:40:05,559 [polychord]   cluster_dir: chains/sn_pantheon/class_pc16_sn/raw_polychord_output/clusters
 2019-09-09 15:40:05,559 [polychord]   cluster_posteriors: True
 2019-09-09 15:40:05,559 [polychord]   compression_factor: 0.36787944117144233
 2019-09-09 15:40:05,559 [polychord]   do_clustering: True
 2019-09-09 15:40:05,559 [polychord]   equals: True
 2019-09-09 15:40:05,560 [polychord]   feedback: 2
 2019-09-09 15:40:05,560 [polychord]   file_root: class_pc16_sn
 2019-09-09 15:40:05,560 [polychord]   grade_dims: [6]
 2019-09-09 15:40:05,560 [polychord]   grade_frac: [6]
 2019-09-09 15:40:05,560 [polychord]   logzero: -1.7976931348623157e+308
 2019-09-09 15:40:05,560 [polychord]   max_ndead: -1
 2019-09-09 15:40:05,560 [polychord]   maximise: False
 2019-09-09 15:40:05,560 [polychord]   nfail: -1
 2019-09-09 15:40:05,560 [polychord]   nlive: 16
 2019-09-09 15:40:05,560 [polychord]   nlives: {}
 2019-09-09 15:40:05,560 [polychord]   nprior: -1
 2019-09-09 15:40:05,560 [polychord]   num_repeats: 30
 2019-09-09 15:40:05,560 [polychord]   posteriors: True
 2019-09-09 15:40:05,560 [polychord]   precision_criterion: 0.001
 2019-09-09 15:40:05,560 [polychord]   read_resume: True
 2019-09-09 15:40:05,560 [polychord]   seed: -1
 2019-09-09 15:40:05,560 [polychord]   write_dead: True
 2019-09-09 15:40:05,560 [polychord]   write_live: True
 2019-09-09 15:40:05,560 [polychord]   write_paramnames: False
 2019-09-09 15:40:05,560 [polychord]   write_prior: True
 2019-09-09 15:40:05,560 [polychord]   write_resume: True
 2019-09-09 15:40:05,560 [polychord]   write_stats: True
 2019-09-09 15:40:05,561 [polychord] Sampling!
PolyChord: MPI is already initilised, not initialising, and will not finalize

PolyChord: Next Generation Nested Sampling
copyright: Will Handley, Mike Hobson & Anthony Lasenby
  version: 1.16
  release: 1st March 2019
    email: wh260@mrao.cam.ac.uk

Run Settings
nlive    :      16
nDims    :       6
nDerived :       8
Doing Clustering
Generating equally weighted posteriors
Generating weighted posteriors
Clustering on posteriors
Writing a resume file tochains/sn_pantheon/class_pc16_sn/raw_polychord_output/class_pc16_sn.resume

forrtl: severe (64): input conversion error, unit 10, file /home/lh561/Documents/Projects/CobayaPrj/chains/sn_pantheon/class_pc16_sn/raw_polychord_output/class_pc16_sn.resume
Image              PC                Routine            Line        Source             
libifcoremt.so.5   00002B097F56398F  for__io_return        Unknown  Unknown
libifcoremt.so.5   00002B097F5A8A59  for_read_seq_fmt_     Unknown  Unknown
libifcoremt.so.5   00002B097F5A5C89  for_read_seq_fmt      Unknown  Unknown
libchord.so        00002B097E4D4F56  read_write_module     Unknown  Unknown
libchord.so        00002B097E4D271E  read_write_module     Unknown  Unknown
libchord.so        00002B097E485722  nested_sampling_m     Unknown  Unknown
libchord.so        00002B097E4F70AF  interfaces_module     Unknown  Unknown
libchord.so        00002B097E4F4628  polychord_c_inter     Unknown  Unknown
libchord.so        00002B097E4F3B72  _Z13run_polychord     Unknown  Unknown
libchord.so        00002B097E4F3860  _Z13run_polychord     Unknown  Unknown
_pypolychord.cpyt  00002B097E23598D  Unknown               Unknown  Unknown
libpython3.6m.so.  00002B093550BA36  _PyCFunction_Fast     Unknown  Unknown
libpython3.6m.so.  00002B09355B55DC  Unknown               Unknown  Unknown
libpython3.6m.so.  00002B09355BC8B3  _PyEval_EvalFrame     Unknown  Unknown
libpython3.6m.so.  00002B09355B3C33  Unknown               Unknown  Unknown
libpython3.6m.so.  00002B09355B57CB  Unknown               Unknown  Unknown
libpython3.6m.so.  00002B09355B5468  Unknown               Unknown  Unknown
libpython3.6m.so.  00002B09355BC8B3  _PyEval_EvalFrame     Unknown  Unknown
libpython3.6m.so.  00002B09355B3C33  Unknown               Unknown  Unknown
libpython3.6m.so.  00002B09355B57CB  Unknown               Unknown  Unknown
libpython3.6m.so.  00002B09355B5468  Unknown               Unknown  Unknown
libpython3.6m.so.  00002B09355BC8B3  _PyEval_EvalFrame     Unknown  Unknown
libpython3.6m.so.  00002B09355B3C33  Unknown               Unknown  Unknown
libpython3.6m.so.  00002B09355B57CB  Unknown               Unknown  Unknown
libpython3.6m.so.  00002B09355B5468  Unknown               Unknown  Unknown
libpython3.6m.so.  00002B09355BC8B3  _PyEval_EvalFrame     Unknown  Unknown
libpython3.6m.so.  00002B09355B3C33  Unknown               Unknown  Unknown
libpython3.6m.so.  00002B09355B57CB  Unknown               Unknown  Unknown
libpython3.6m.so.  00002B09355B5468  Unknown               Unknown  Unknown
libpython3.6m.so.  00002B09355BC8B3  _PyEval_EvalFrame     Unknown  Unknown
libpython3.6m.so.  00002B09355B24AA  PyEval_EvalCodeEx     Unknown  Unknown
libpython3.6m.so.  00002B09355B1959  PyEval_EvalCode       Unknown  Unknown
libpython3.6m.so.  00002B09355FF48E  PyRun_FileExFlags     Unknown  Unknown
libpython3.6m.so.  00002B09355FEF05  PyRun_SimpleFileE     Unknown  Unknown
libpython3.6m.so.  00002B093561C6DC  Py_Main               Unknown  Unknown
python3            0000000000401E69  main                  Unknown  Unknown
libc-2.17.so       00002B09365863D5  __libc_start_main     Unknown  Unknown
python3            0000000000401CA9  Unknown               Unknown  Unknown
```

**Comment by JesusTorrado** [comment] 2019-09-10 09:51
Hi Lukas,

That's an Intel Fortran error, apparently. I am not able to reproduce it right now (your input resumes fine using my `gfortran` 7.4. I'd suggest you either:

a) use gfortran >= 6.4 (preferred option)
b) try to reproduce the issue running the `run_pypolychord.py`, interrupting+resuming, from the `modules/code/PolyChordLite` folder of your installation. If it fails, report it in the [official PolyChord repo](https://github.com/PolyChord/PolyChordLite). If works, please let me know (though I'd be quite surprised).

Please, let me know of the outcome so that we decide whether to close the issue or not yet.

**Comment by lukashergt** [comment] 2019-09-10 10:34
> a) use gfortran >= 6.4 (preferred option)

I'm using gfortran version 7.2.0

> b) try to reproduce the issue running the `run_pypolychord.py`, interrupting+resuming, from the `modules/code/PolyChordLite` folder of your installation. If it fails, report it in the [official PolyChord repo](https://github.com/PolyChord/PolyChordLite). If works, please let me know (though I'd be quite surprised).

Resuming with `run_pypolychord.py` works fine. 

Also, I can run MontePython with PolyChord and resuming works fine there (other issues there, which is why I wanted to give Cobaya a try).


> I am not able to reproduce it right now (your input resumes fine using my `gfortran` 7.4.

This leaves me puzzled...

**Comment by lukashergt** [comment] 2019-09-18 01:49
Hi @JesusTorrado,

>  Is there any chance at all that you had inadvertently used `ifort` instead of `gfortran`?

Indeed it was compiling with `ifort` instead of `gfortran`. Forcing compilation with `gfortran` makes the resuming work with the SN likelihood. Unfortunately now I get errors when trying to run with Planck, so I'm still stuck, but that would be for a separate issue.

--- 

Do you know a reason why `ifort` shouldn't work? 

It works with PolyChord's `run_pypolychord.py` and also with `MontePython`, so I am surprised that it shouldn't work with Cobaya. I tried with intel/2017.4, intel/2018.4, and intel/2019.3. Resuming always failed...

**Comment by JesusTorrado** [comment] 2019-09-18 05:07
Hi @lukashergt 

No, honestly I don't know why it wouldn't work with Intel, even when it's supposed to. I am inclined to doubt Cobaya has much to do with it, at least vs MontePython, since they both deal with PolyChord in a very similar way, and the Python part of the code should not affect how Fortran writes and reads files, which is apparently what's failing there. I am puzzled.

Let's close this then, at least until something else on the issue comes up.

Please, do let me know about the Planck errors!

**Closed by JesusTorrado** 2019-09-18 05:07 UTC

**Comment by lukashergt** [comment] 2019-09-27 16:03
The problem appears to be the `logzero` value. Currently the default was to set `logzero` in the PolyChord yaml file to `np.nan_to_num(-np.inf)` which leads to unreadable entries in the resume file (writeable but unreadable for some reason...). Fixing logzero to `-1e300` seems to work.

I've also looked into MontePython where they seem to use their own `boundary_loglike=-1e30` value. Not sure which particular value (`-1e30` or `-1e300`) would be the most desirable here, but I think it would be better to stay within double precision for this and avoid using `np.nan_to_num`. 

I've created PR #42 for this.

**Comment by williamjameshandley** [comment] 2019-09-27 16:32
I would recommend `-1e30`, given that it's both the [MontePython](https://github.com/brinckmann/montepython_public) and [cosmomc](https://github.com/cmbant/CosmoMC) default, so people will be used to that in a cosmological context

**Comment by lukashergt** [comment] 2019-09-27 16:44
> I would recommend `-1e30`, given that it's both the [MontePython](https://github.com/brinckmann/montepython_public) and [cosmomc](https://github.com/cmbant/CosmoMC) default, so people will be used to that in a cosmological context

It's also within single precision, so yeah, maybe `-1e30` is the better choice...

**Comment by JesusTorrado** [comment] 2019-10-02 13:55
I am afraid I disagree there: since `-1e300` appears to work, let's use it, since it is a much safer value (we can safely assume double precision). I'll update and merge #42

**Comment by lukashergt** [comment] 2019-10-02 14:04
> I am afraid I disagree there: since `-1e300` appears to work, let's use it, since it is a much safer value (we can safely assume double precision). I'll update and merge #42

Reverting the last commit will do that.

**Comment by williamjameshandley** [comment] 2019-10-02 17:01
>I am afraid I disagree there: since -1e300 appears to work, let's use it, since it is a much safer value (we can safely assume double precision). I'll update and merge #42

This is fine, although it's worth pointing out that it's a change from the default (i.e. what other people's modifications of either class or camb might assume) from both cosmomc and montepython. A loglikelihood of -1000000000000000000000000000000 is pretty safe as a value anyway.

**Comment by JesusTorrado** [comment] 2019-10-04 15:56
I'll keep that change of defaults in mind in case something possibly related to that fails in the future, thanks!

**Comment by williamjameshandley** [comment] 2020-01-15 07:00
Hi @JesusTorrado [This issue](https://github.com/williamjameshandley/anesthetic/issues/70) uncovered by @lukashergt  is an example where -1e300 is too large as a default logzero, since computing a variance with this quantity generates overflow errors (whilst -1e30) does not. This is not something I anticipated, but is likely what drove the original choice of a default of -1e30 for both CosmoMC and MontePython.

**Comment by JesusTorrado** [comment] 2020-01-15 09:59
Thanks @williamjameshandley! Ok, I'll make it -1e30 as a default for PolyChord in the next version (though I'd recommend making PolyChord and Anesthetic more resilient to overflows, if possible).
